In [4]:
from alfpy.utils import distmatrix
from alfpy.utils import seqrecords
from alfpy import ncd

seq_records = seqrecords.SeqRecords()
seq_records.add('seq1', 'MKSTGWHF')
seq_records.add('seq2', 'MKSSSSTGWGWG')
seq_records.add('seq3', 'MKSTLKNGTEQ')  

dist = ncd.Distance(seq_records)
matrix = distmatrix.create(seq_records.id_list, dist)


In [15]:
help(matrix)

Help on Matrix in module alfpy.utils.distmatrix object:

class Matrix(builtins.object)
 |  Matrix(id_list, data)
 |  
 |  Distance matrix
 |  
 |  Attributes:
 |      id_list (list): list of sequence identifiers
 |      data (ndarray): 2-D array of distance values between pairs of seqs
 |  
 |  Methods defined here:
 |  
 |  __init__(self, id_list, data)
 |      Example:
 |          >>> id_list = ['seq1', 'seq2', 'seq3']
 |          >>> data
 |          [[ 0.          0.3531587   0.35509333]
 |           [ 0.3531587   0.          0.295394  ]
 |           [ 0.35509333  0.295394    0.        ]]
 |          >>> matrix = Matrix(id_list, data)
 |  
 |  __iter__(self)
 |      Iterate over a distance matrix.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  display(self, f='phylip', decimal_places=7)
 |      Write a distance matrix to the screen.
 |  
 |  format(self, decimal_places=7)
 |  
 |  highcharts(self)
 |      Return a distance matrix as a list in the Highcharts format.
 | 

In [17]:
matrix.display()

   3
seq1       0.0000000 0.4117647 0.4736842
seq2       0.4117647 0.0000000 0.5789474
seq3       0.4736842 0.5789474 0.0000000


In [16]:
a = matrix.highcharts()
a

[[0, 1, 0.7112299465240641, 0.4117647058823529],
 [0, 2, 0.8181818181818181, 0.47368421052631576],
 [1, 2, 1.0, 0.5789473684210527]]

In [20]:
matrix.normalize()
matrix.display()

   3
seq1       0.0000000 0.7112299 0.8181818
seq2       0.7112299 0.0000000 1.0000000
seq3       0.8181818 1.0000000 0.0000000


In [25]:
matrix.writer(a, 'pairwise', 7)

AttributeError: 'str' object has no attribute 'write'

In [26]:
matrix.display()

   3
seq1       0.0000000 0.7112299 0.8181818
seq2       0.7112299 0.0000000 1.0000000
seq3       0.8181818 1.0000000 0.0000000


In [27]:
a = matrix.display()

   3
seq1       0.0000000 0.7112299 0.8181818
seq2       0.7112299 0.0000000 1.0000000
seq3       0.8181818 1.0000000 0.0000000


In [55]:
import io

a = io.StringIO()

In [56]:
matrix.writer(a, 'phylip', 7)

In [60]:
a.seek(0)
a.read()


'   3\nseq1       0.0000000 0.7112299 0.8181818\nseq2       0.7112299 0.0000000 1.0000000\nseq3       0.8181818 1.0000000 0.0000000\n'

In [72]:
import pandas as pd
a.seek(0)
data = pd.read_csv(a,sep=" +",skiprows=[0],header=None,index_col=0)
data.index.name = None
data.columns = data.index
data

/var/folders/yl/1prc755j381357z7mbt63w2c0000gp/T/ipykernel_38752/2959782491.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv(a,sep=" +",skiprows=[0],header=None,index_col=0)


seq1     seq2      seq3
seq1  0.000000  0.71123  0.818182
seq2  0.711230  0.00000  1.000000
seq3  0.818182  1.00000  0.000000

In [73]:
data.values

array([[0.       , 0.7112299, 0.8181818],
       [0.7112299, 0.       , 1.       ],
       [0.8181818, 1.       , 0.       ]])

In [74]:
temp = data.values
temp

array([[0.       , 0.7112299, 0.8181818],
       [0.7112299, 0.       , 1.       ],
       [0.8181818, 1.       , 0.       ]])

In [76]:
temp.shape

(3, 3)

In [77]:
pd.DataFrame(temp,index=data.index, columns=data.index)

seq1     seq2      seq3
seq1  0.000000  0.71123  0.818182
seq2  0.711230  0.00000  1.000000
seq3  0.818182  1.00000  0.000000